"""empty message

Revision ID: 579fde79c898
Revises: 
Create Date: 2023-09-09 12:10:06.019258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579fde79c898'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('team',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('teamname', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('league', sa.String(length=20), nullable=True),
    sa.Column('record', sa.String(length=200), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('user')
    # ### end Alembic commands ###
